### ISSUE TITLE
Add descriptions for interpolation options

### ISSUE THREAD

**Issue by mattldawson** [NCAR/tuv-x#110]
There are currently four interpolation schemes labelled `interp1`..`interp4`. These should be given descriptive names. More detailed descriptions of the specific approaches employed by each scheme should be added to the documentation.  Any configuration options for choosing a scheme should be modified to use the descriptive names.

**Comment by mattldawson** [comment]
From Stacy:
> I've looked over
> the inter1 .. inter4 business and here is what I surmise:
> 
> (1).  inter1 is a classic, linear, non-conserving interpolator
> (2).  inter2 is a linear, conserving interpolator using the trapezoidal rule to compute the
>         "area under the curve"
> (3).   inter3 is the same as (2) except the "area under the curve" is computed by
>          holding the function to the value at the lower edge of an interval.
>          This also has the Foldin switch which folds values from the source
>           grid into the last interval of the destination grid
> (4).   As far as I can tell there is no difference between (3) and (4)

**Comment by K20shores** [comment]
Related #12
