### ISSUE TITLE
Record and automate release

### ISSUE THREAD

**Issue by K20shores** [NCAR/tuv-x#130]
Document our release process in our internal google drive and automate the release as much as possible

things that should be automated

- Versioned documentation
- Add a link to the main branches documentation with the version switcher

**Comment by K20shores** [comment]
The version number will need to be passed into conf.py when the github action runs somehow so that the version number can be automatically updated in the version switcher

**Comment by K20shores** [comment]
as a bonus, adding the available branches into the switcher automatically would be cool, but not quite sure how they would ever get removed.

**Comment by zmoon** [comment]
Could also consider using https://readthedocs.org/ (if you hadn't already)

**Comment by K20shores** [comment]
@zmoon yes, thanks for bringing that to our attention and we are aware of that. Github pages works well enough for this because the theme we chose has a version switcher. This task is specifically meant to make the release process easier to do since there is at least one step that has to be done by hand. And, more importantly, documenting what all a release entails internally so that future NCAR developers are aware of how to maintain this project.

**Comment by K20shores** [comment]
@mattldawson after our release yesterday, I think we may not need this ticket anymore. Yesterday was pretty straight forward. What do you think?

**Comment by mattldawson** [comment]
I agree - no need to over-automate
