### ISSUE TITLE
Remove output to stdout from all TUV-x library code

### ISSUE THREAD

**Issue by mattldawson** [NCAR/tuv-x#143]

**Comment by K20shores** [comment]
@mattldawson I vote we close this one. The only output is in the files listed below. Anything written to stdout is an error messages right before we crash the application.

- core.F90
- cross_sections/hno3-oh_no2.F90
- cross_sections/tint.F90
- cross_sections/o3_tint.F90
- cross_sections/no2_tint.F90
- cross_sections/rono2.F90
- diagnostic_util.F90
- la_sr_bands.F90
- linear_algebras/linpack.F90
- netcdf.F90
- photolysis_rates.F90
- quantum_yield.F90
- quantum_yields/tint.F90
- tuvx.F90
- util.F90

**Comment by mattldawson** [comment]
sounds good to me!
