### ISSUE TITLE
Build and run CESM

### ISSUE THREAD

**Issue by K20shores** [NCAR/tuv-x#179]
CESM Quickstart instructions: https://escomp.github.io/CESM/versions/master/html/index.html

**Comment by mattldawson** [comment]
Cheyenne
========

Following the CESM Quick Start Guide and instructions Francis provided earlier, I was able to run on Cheyenne with:

```
git clone -b release-cesm2.1.3 https://github.com/ESCOMP/CESM.git my_cesm_sandbox
cd my_cesm_sandbox
git checkout release-cesm2.2.0
./manage_externals/checkout_externals
```
May need to follow these instructions in the Quick Start Guide at this point:

> When contacting the Subversion server for the first time, you may need to accept an authentication certification. If you experience problems such as checkout_externals hanging: Run svn ls https://svn-ccsm-models.cgd.ucar.edu/ww3/release_tags, permanently accepting the certificate when prompted, then retry the CESM download (starting over at the top of these instructions).

After that, I set `CASE_DIR` to the (not yet existing) folder for my new "case" and ran (from the `my_cesm_sandbox` folder):

```
cd cime/scripts
create_newcase --compset FHIST --res f09_f09_mg17 --case $CASE_DIR
cd $CASE_DIR
case.setup
qcmd -- case.build
case.submit
```

The results end up in `/glade/scratch/$USER/$CASE_NAME` where `$CASE_NAME` is the name of the folder `$CASE_DIR` points to.

Local
=====

There is a GitHub repo with Docker scripts for running CESM [here](https://github.com/ESCOMP/ESCOMP-Containers.git).

```
git clone https://github.com/ESCOMP/ESCOMP-Containers.git
cd ESCOMP-Containers/CESM/2.2
```

I had a problem with an invalid SSL certificate cloning a subversion repo. Following advice [here](https://stackoverflow.com/questions/9257323/bypass-ssl-certificate-validation-in-subversion), I modified the `Dockerfile` in this folder adding a `sed` command just prior to the call to `manage_externals`:

```
# Install CESM:
COPY Files/ea002e626aee6bc6643e8ab5f998e5e4 /root/.subversion/auth/svn.ssl.server/
RUN sudo mkdir -p /opt/ncar && \
    cd /opt/ncar && \
    sudo git clone -b release-cesm2.2.0 https://github.com/ESCOMP/cesm.git cesm2 && \
    cd cesm2 && \
    sudo sed -i "s/'checkout', '--quiet'/'checkout', '--quiet', '--non-interactive', '--trust-server-cert'/" manage_externals/manic/repository_svn.py && \
    sudo ./manage_externals/checkout_externals
```

This bypassed the problem. I will open an issue on the `ESCOMP-Containers` repo.

After that, I followed these instructions:

```
docker build -t cesm-test .
mkdir cesm-data
docker run -it -v $(pwd)/cesm-data:/home/user cesm-test
create_newcase --case test1 --compset F2000climo --res f19_g17 --run-unsupported
cd test-1
./xmlchange NTASKS=4
./case.setup
./case.build
./case.submit
```

The build and download of data were successful, but I got an error when running the model (in the cesm log file):
```
 TASK#  NAME
  0  4f6d84f1bd35
  1  4f6d84f1bd35
  2  4f6d84f1bd35
  3  4f6d84f1bd35
 WARNING: Rearr optional argument is a pio2 feature, ignored in pio1
 WARNING: Rearr optional argument is a pio2 feature, ignored in pio1
 WARNING: Rearr optional argument is a pio2 feature, ignored in pio1
 WARNING: Rearr optional argument is a pio2 feature, ignored in pio1
 WARNING: Rearr optional argument is a pio2 feature, ignored in pio1
 pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         235 : Unknown error in file operation
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
 pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         235 : Unknown error in file operation
 pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         235 : Unknown error in file operation
 pio_support::pio_die:: myrank=          -1 : ERROR: ionf_mod.F90:         235 : Unknown error in file operation
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
```

Seems like it might be incorrect settings for which MPI tasks do i/o - will continue to investigate, but at least this can be used to check whether the model compiles.

**Comment by stacywalters** [comment]
Matt, perhaps someone in CGD could help pinpoint the problem?

**Comment by mattldawson** [comment]
> Matt, perhaps someone in CGD could help pinpoint the problem?

I will ask Brian. The [ESCOMP_Containers repo](https://github.com/ESCOMP/ESCOMP-Containers) says that it is still under development, so it may be that they are not completely working yet.

**Comment by mattldawson** [comment]
Modeling2
========

There is no machine configuration for modeling2 in the CAM or CESM repo. Following Francis's advice, I copied his `~/.cime/` folder and edited the `.cime/config_machines.xml` file to replace all the paths that included his user name with mine, and ensured that I had folders set up at these paths. I left the `DIN_LOC_ROOT` and `DIN_LOC_ROOT_CLMFORC` paths pointing to Francis's folders because the input data files are large and the recommendation in the CESM documentation is to have a shared input data folder for the machine.

I also created a `~/bin/` folder and copied Francis's `~/bin/cprnc` executable to it. I also created a sym link for CMake:

```
ln -s /usr/bin/cmake3 ~/bin/cmake
```

and added this line to my `~/.bashrc` file:

```
export PATH=".:$HOME/bin:"$PATH
```

I was then able to follow the same instructions for running a case as above for Cheyenne

**Comment by K20shores** [comment]
For the record, I tried and failed to run CESM on my local machine by building from source. I had to install ESMF myself since that apparently isn't installed by CESM. I also had to jump through some hoops to install the XML package for perl. In the end, it was far more work than running on Cheyenne or Modeling2 with the instructions that Matt left above.
