### ISSUE TITLE
Post URL of model results from Quick TUV-x calculator

### ISSUE THREAD

**Issue by carl-drews** [NCAR/tuv-x#264]
User will see a directory of NetCDF files to download:

modeling2:/home/drews/TUV-x/stage/20230410-144427--029087> ls -lh
total 129M
lrwxrwxrwx 1 drews support  45 Apr 10 14:44 data -> /home/drews/TUV-x/tuvx-build/tuv-x/build/data/
-rw-r--r-- 1 drews support 64M Apr 10 14:44 [dose_rates.nc](http://dose_rates.nc/)
-rw-r--r-- 1 drews support 65M Apr 10 14:44 [photolysis_rate_constants.nc](http://photolysis_rate_constants.nc/)
-rw-r--r-- 1 drews support 67K Apr 10 14:44 tuvx_config.json
modeling2:/home/drews/TUV-x/stage/20230410-144427--029087>

**Comment by K20shores** [comment]
@dattilo would you have time to do this sometime in the next two weeks?

**Comment by carl-drews** [comment]
From: Garth D'Attilo <dattilo@ucar.edu>
Date: Tue, Apr 11, 2023 at 10:36 AM
Subject: Re: WebTUV-x calculator results accessible
To: Carl Drews <drews@ucar.edu>


Hi Carl,
   This has been setup and a separate directory created:
        /net/modeling2/data/TUV-x
Take care,
Garth

**Comment by carl-drews** [comment]
Quick TUV-x user now gets a download link at the bottom of the text results:

```
335 quantum yield CF2O+hv->Products         1.00000e+00
. . .
Download TUV-x output at: https://www.acom.ucar.edu/tuv-x/STAGE/20230411-151130--628904/
End time remote: 2023-04-11 15:11:32.868862 Local
```

And the directory listing looks like this:

```
Name	Modified	Size
dose_rates.nc	2023-04-11 15:11:31	65MB
photolysis_rate_constants.nc	2023-04-11 15:11:31	65MB
tuvx_config.json	2023-04-11 15:11:30	67KB
tuvxDir.txt	2023-04-11 15:11:32	43B
```

**Comment by carl-drews** [comment]
Issue is completed.
https://www.acom.ucar.edu/Models/TUV/Interactive_TUV/tuv-x.shtml
