### ISSUE TITLE
Bug with specified solar zenith angle

### ISSUE THREAD

**Issue by mattldawson** [NCAR/tuv-x#279]
This configuration:

https://www.acom.ucar.edu/tuv-x/STAGE/20230810-170755--740058/tuvx_config.json

on modeling2 using TUV-x built with:
```

modeling2:/home/drews/TUV-x/tuvx-build> cat goBuild
./build_tuvx_modeling2_gnu.sh
```

produces the error in the attached file: [InputOption2-error01.txt](https://github.com/NCAR/tuv-x/files/12317750/InputOption2-error01.txt)

**Comment by carl-drews** [comment]
That link to tuvx_config.json will expire in 48 hours; I have attached the file itself.
Um . . . can we allow JSON files to be attached?

**Comment by carl-drews** [comment]
Here is the config json file with a .txt extension that should be removed before using it.
[tuvx_config-20230810.json.txt](https://github.com/NCAR/tuv-x/files/12317807/tuvx_config-20230810.json.txt)
