### ISSUE TITLE
Add heating rate calculations

### ISSUE THREAD

**Issue by mattldawson** [NCAR/tuv-x#47]
From @fvitt - Rather than adopting the changes in this PR, I propose implementing a separate method the the photolysis_rates class for calculating the chemical potential energy which could be invoked something like

```
cpe(:) = obj%chemPotEnergy('ReactionName',...)
```
These parameters could be be set in the json configuration file for the reactions that contribute to chemical potential heating:
```
  real(r8), parameter :: wc_o2_a     = 175.05_r8   ! (nm)
  real(r8), parameter :: wc_o2_b     = 242.37_r8   ! (nm)
  real(r8), parameter :: wc_o3_a     = 310.32_r8   ! (nm)
  real(r8), parameter :: wc_o3_b     = 1179.87_r8  ! (nm)
```
See https://github.com/fvitt/CAM/blob/e37cebbd4edc7a96b57a50e4d9332e84adba5b9d/src/chemistry/mozart/mo_tuvx.F90#L138

Calculations of the bond dissociation energies, as is done here
https://github.com/fvitt/CAM/blob/e37cebbd4edc7a96b57a50e4d9332e84adba5b9d/src/chemistry/mozart/mo_tuvx.F90#L485

could be done internal to the photolysis_rates, maybe at construction time.

**Comment by mattldawson** [comment]
@fvitt - is there a description I can include on the meaning of the `a` and `b` energy terms?

**Comment by fvitt** [comment]
> @fvitt - is there a description I can include on the meaning of the `a` and `b` energy terms?

Is this in reference to the `wc_*` parameters listed above?  Those are wavelength thresholds for `jo2_a`, `jo2_b`, `jo3_a`, and `jo3_b` reactions. The `a` and `b` indicate different dissociation channels.  Doug weigh in on this to clarify (don't know his github handle).
