### ISSUE TITLE
Add clang-tidy action

### ISSUE THREAD

**Issue by mattldawson** [NCAR/tuv-x#77]
With the implementation of the C++/CUDA Delta Eddington solver, it would be good to have a clang-tidy action similar to what is in MICM (https://github.com/NCAR/micm/blob/20015ed0ef96ffa207fb991f58ec0baff19f816a/.github/workflows/clang-tidy.yml#L1)

**Comment by boulderdaze** [comment]
Hi @mattldawson, @K20shores, was this [config_yaml.h](https://github.com/NCAR/tuv-x/blob/main/include/tuvx/util/config_yaml.h) specifically named with `h` extension to mean that is C header? Are we applying `camel case` for the functions in this file or stick with `snake case`?

**Comment by mattldawson** [comment]
I think that was the idea, but I'm not sure if we ever really thought through the naming for header files that are included from both C and C++ source files. It would be fine with me to use `.hpp` if that fits better with the `clang-tidy` recommendations.

Same for the function names - I'd say whatever style is recommended is fine by me.
