### ISSUE TITLE
Failed compilation of TUV-x on Derecho with Intel compilers

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/tuv-x#84]
As identified by the PR #83 , currently we can not build all the TUV-x tests on Derecho with the Intel compilers (we do get the `tuv-x` executable generated though).

The compilation error message looks like:
```
Invalid_sym_id for THIS, -268435456
/glade/derecho/scratch/sunjian/tmp/ifortgpInVx.i90: catastrophic error: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /glade/derecho/scratch/sunjian/tuv-x/test/oldtuv/grid/from_csv_file.type.F90 (code 1)
```

**Comment by K20shores** [comment]
It's a regression test that fails. We could bypass this ICE by trying to only compile tests for tuvx that aren't regression tests. It's not worth our time to fix an ICE in regression test code, in my opinion

**Comment by sjsprecious** [comment]
According to Kyle's suggestion, we have some issues with NAG and GCC/13 compilers for TUV Fortran regression tests. It seems that the ICE from Intel compiler is also triggered by those tests.

A better solution is to define a new CMake variable and bypass the old regression test for Fortran explicitly. This new CMake variable will replace the long check condition here: https://github.com/NCAR/tuv-x/blob/main/test/CMakeLists.txt#L29-L34.
